import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsString, IsNumber, IsArray, IsOptional, Min } from 'class-validator';

export class CreateMenuDto {
  @ApiProperty({
    description: 'Name of the menu item',
    example: 'Ayam Geprek Spesial',
  })
  @IsString()
  name: string;

  @ApiProperty({
    description: 'Category of the menu item',
    example: 'food',
    enum: ['food', 'drinks'],
  })
  @IsString()
  category: string;

  @ApiProperty({
    description: 'Calories count',
    example: 520,
    minimum: 0,
  })
  @IsNumber()
  @Min(0)
  calories: number;

  @ApiProperty({
    description: 'Price in IDR',
    example: 18000,
    minimum: 0,
  })
  @IsNumber()
  @Min(0)
  price: number;

  @ApiProperty({
    description: 'List of ingredients',
    example: ['chicken', 'chili', 'batter', 'garlic'],
    type: [String],
  })
  @IsArray()
  @IsString({ each: true })
  ingredients: string[];

  @ApiPropertyOptional({
    description: 'Description of the menu item. If not provided, will be auto-generated by AI',
    example: 'Hand-pounded crispy battered chicken crushed with vibrant sambal',
  })
  @IsOptional()
  @IsString()
  description?: string;
}
